# site settings
title: Ethan
subtitle: by HTML5 UP
email: ethancboone@gmail.com
description: Student Naval Aviator, Data Scientist, and Aerospace Engineer<br /> Welcome to my site!.
baseurl: "/" # the subpath of your site, e.g. /blog
url: 
author:
street_address:
city: Pensacola
state: FL
zip_code:
country: United States of America
phone: (443) 262-6985

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/ethancboone
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/ethan-boone-b07b95216/
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
